"""
=============================================================
  MODULE 10 — MODEL ROUTER (Offline + Online)
  Routes responses between local rule-based intelligence and
  optional online LLM providers.

  Online providers currently supported:
    - OpenAI Chat Completions API
    - Ollama local server API
=============================================================
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from typing import Optional, Tuple

import requests


TAMIL_CHAR_RE = re.compile(r"[\u0B80-\u0BFF]")


@dataclass
class OnlineResult:
    """Represents one response generated by an online provider."""

    text: str
    provider: str
    model: str
    source: str = "online"


class ModelRouter:
    """
    Handles online model routing with deterministic fallback order.

    Fallback order:
      1) preferred provider (if set)
      2) OpenAI (if API key exists)
      3) Ollama (if endpoint available)
    """

    def __init__(self, timeout: int = 25):
        self.timeout = timeout
        self.session = requests.Session()

        self.openai_api_key = os.getenv("OPENAI_API_KEY", "").strip()
        self.openai_model = os.getenv("OPENAI_MODEL", "gpt-4o-mini").strip()

        self.ollama_base_url = os.getenv("OLLAMA_BASE_URL", "http://127.0.0.1:11434").strip().rstrip("/")
        self.ollama_model = os.getenv("OLLAMA_MODEL", "llama3.1").strip()

    # -- public helpers -------------------------------------------------

    def online_enabled(self) -> bool:
        """Return True when any online provider is likely available."""
        if self.openai_api_key:
            return True
        return self._check_ollama_health()

    def provider_status(self) -> dict:
        """Human-readable provider availability details."""
        return {
            "openai": bool(self.openai_api_key),
            "ollama": self._check_ollama_health(),
            "openai_model": self.openai_model,
            "ollama_model": self.ollama_model,
        }

    def language_hint(self, text: str) -> str:
        """Lightweight language hint for bilingual replies."""
        if TAMIL_CHAR_RE.search(text or ""):
            return "ta"
        return "en"

    def generate_online_reply(
        self,
        user_text: str,
        emotion: str = "neutral",
        user_name: str = "",
        preferred_provider: str = "auto",
        persona_name: str = "JARVIS",
        context_turns: Optional[list] = None,
        factual_context: str = "",
        response_style: str = "friendly",
    ) -> Tuple[Optional[OnlineResult], Optional[str]]:
        """
        Generate an online response.

        Returns
        -------
        (OnlineResult|None, error_message|None)
        """
        if not user_text.strip():
            return (None, "empty_input")

        lang = self.language_hint(user_text)
        provider_chain = self._provider_chain(preferred_provider)

        # Use the last few conversation turns to improve continuity.
        context_turns = context_turns or []
        context_turns = context_turns[-5:]

        for provider in provider_chain:
            if provider == "openai":
                result, err = self._ask_openai(
                    user_text=user_text,
                    emotion=emotion,
                    user_name=user_name,
                    lang=lang,
                    persona_name=persona_name,
                    context_turns=context_turns,
                    factual_context=factual_context,
                    response_style=response_style,
                )
                if result:
                    return (result, None)
                if err in ("auth_missing", "provider_unavailable"):
                    continue
                # Any other error: continue fallback chain.
                continue

            if provider == "ollama":
                result, err = self._ask_ollama(
                    user_text=user_text,
                    emotion=emotion,
                    user_name=user_name,
                    lang=lang,
                    persona_name=persona_name,
                    context_turns=context_turns,
                    factual_context=factual_context,
                    response_style=response_style,
                )
                if result:
                    return (result, None)
                if err == "provider_unavailable":
                    continue
                continue

        return (None, "all_providers_failed")

    # -- provider order -------------------------------------------------

    def _provider_chain(self, preferred_provider: str) -> list:
        preferred = (preferred_provider or "auto").lower().strip()
        if preferred == "openai":
            return ["openai", "ollama"]
        if preferred == "ollama":
            return ["ollama", "openai"]
        return ["openai", "ollama"]

    # -- OpenAI ---------------------------------------------------------

    def _ask_openai(
        self,
        user_text: str,
        emotion: str,
        user_name: str,
        lang: str,
        persona_name: str,
        context_turns: list,
        factual_context: str,
        response_style: str,
    ) -> Tuple[Optional[OnlineResult], str]:
        if not self.openai_api_key:
            return (None, "auth_missing")

        url = "https://api.openai.com/v1/chat/completions"

        # Keep the persona and output constrained for assistant UX.
        system_prompt = (
            f"You are {persona_name}, a friendly futuristic assistant for a Windows desktop. "
            "Be clear, practical, and emotionally warm. "
            "Keep most responses between 1 and 6 short lines. "
            "If user language appears Tamil, reply in Tamil or Tanglish naturally. "
            "If user language appears English, reply in English. "
            "Detected user emotion is: "
            f"{emotion}. "
            f"Response style target is: {response_style}. "
            "Prioritize factual correctness over creativity. "
            "If you are unsure about a fact, say that clearly instead of guessing. "
            "Never invent sources, numbers, or events. "
            "Do not claim you executed OS commands unless explicitly told that command execution already happened. "
            "Avoid harmful guidance."
        )

        messages = [{"role": "system", "content": system_prompt}]

        if user_name:
            messages.append(
                {
                    "role": "system",
                    "content": f"User name is {user_name}. Use their name occasionally, not every sentence.",
                }
            )

        factual_context = (factual_context or "").strip()
        if factual_context:
            messages.append(
                {
                    "role": "system",
                    "content": (
                        "Use the following factual context when relevant. "
                        "If it conflicts with your memory, prefer this context:\n"
                        f"{factual_context}"
                    ),
                }
            )

        if context_turns:
            for turn in context_turns:
                user_text_turn = str(turn.get("user", "")).strip()
                ai_text_turn = str(turn.get("ai", "")).strip()
                if user_text_turn:
                    messages.append({"role": "user", "content": user_text_turn})
                if ai_text_turn:
                    messages.append({"role": "assistant", "content": ai_text_turn})

        messages.append({"role": "user", "content": user_text})

        payload = {
            "model": self.openai_model,
            "messages": messages,
            "temperature": 0.45,
            "max_tokens": 400,
        }

        headers = {
            "Authorization": f"Bearer {self.openai_api_key}",
            "Content-Type": "application/json",
        }

        try:
            response = self.session.post(url, headers=headers, json=payload, timeout=self.timeout)
            if response.status_code >= 400:
                return (None, "provider_unavailable")

            data = response.json()
            choices = data.get("choices", [])
            if not choices:
                return (None, "malformed_response")

            text = (
                choices[0]
                .get("message", {})
                .get("content", "")
                .strip()
            )

            if not text:
                return (None, "empty_response")

            return (
                OnlineResult(text=text, provider="openai", model=self.openai_model, source="online"),
                "",
            )
        except requests.RequestException:
            return (None, "provider_unavailable")
        except Exception:
            return (None, "unexpected_error")

    # -- Ollama ---------------------------------------------------------

    def _check_ollama_health(self) -> bool:
        """Best-effort health check for local Ollama server."""
        try:
            res = self.session.get(f"{self.ollama_base_url}/api/tags", timeout=2)
            return res.status_code == 200
        except Exception:
            return False

    def _ask_ollama(
        self,
        user_text: str,
        emotion: str,
        user_name: str,
        lang: str,
        persona_name: str,
        context_turns: list,
        factual_context: str,
        response_style: str,
    ) -> Tuple[Optional[OnlineResult], str]:
        if not self._check_ollama_health():
            return (None, "provider_unavailable")

        url = f"{self.ollama_base_url}/api/chat"

        system_prompt = (
            f"You are {persona_name}, a friendly assistant running locally on Windows. "
            f"Detected user emotion is {emotion}. Respond in {'Tamil/Tanglish' if lang == 'ta' else 'English'} "
            f"with practical and empathetic tone. Response style target is: {response_style}. "
            "Keep responses concise and useful. "
            "Prioritize factual correctness. If not sure, say you are not sure and avoid guesses."
        )

        messages = [{"role": "system", "content": system_prompt}]

        if user_name:
            messages.append(
                {
                    "role": "system",
                    "content": f"User name is {user_name}. Use it naturally sometimes.",
                }
            )

        factual_context = (factual_context or "").strip()
        if factual_context:
            messages.append(
                {
                    "role": "system",
                    "content": (
                        "Use this factual context when relevant and do not contradict it unless clearly outdated:\n"
                        f"{factual_context}"
                    ),
                }
            )

        for turn in context_turns:
            u = str(turn.get("user", "")).strip()
            a = str(turn.get("ai", "")).strip()
            if u:
                messages.append({"role": "user", "content": u})
            if a:
                messages.append({"role": "assistant", "content": a})

        messages.append({"role": "user", "content": user_text})

        payload = {
            "model": self.ollama_model,
            "stream": False,
            "messages": messages,
            "options": {
                "temperature": 0.45,
            },
        }

        try:
            response = self.session.post(url, json=payload, timeout=self.timeout)
            if response.status_code >= 400:
                return (None, "provider_unavailable")

            data = response.json()
            text = data.get("message", {}).get("content", "").strip()
            if not text:
                return (None, "empty_response")

            return (
                OnlineResult(text=text, provider="ollama", model=self.ollama_model, source="online"),
                "",
            )
        except requests.RequestException:
            return (None, "provider_unavailable")
        except Exception:
            return (None, "unexpected_error")
